{% set data = load_setup_py_data() %}

package:
  name: sd2
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - cantera

test:
  imports:
    - sd2

  requires:
    - pytest
    - pytest-cov

  commands:
    - pytest -vv --pyargs sd2

about:
  home: data['url']
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: data['description']
  description: data['long_description']
  dev_url: data['url']
